### ISSUE TITLE
Предложение: тег [Offline Ban] в переводе и поддержка нескольких флагов для исключений

### ISSUE THREAD

**Issue by kilroy98** [Grey-rus/offlineban#2]
Предлагаю вывести тег [Offline Ban] в перевод, чтобы его можно было раскрасить.
Ну и после моих "исследований" выяснилось, что в исключениях читается только один флаг. Я вот, например, хочу указать флаги b и z в исключения, дабы админы в списке отключённых не светились, но плагин считывает только первый флаг, который указан в кавычках, второй он просто игнорирует.

**Comment by Grey-rus** [comment]
Тег я перенесу, а про флаги так задумывалось.  И если указан b то на z тоже будет действовать потому что в нём эти флаги уже есть, вроде должно так работать.

**Comment by kilroy98** [comment]
Только что ещё раз проверил, в cfg указан флаг b, у меня соответственно флаг z и в списке отключившихся меня показывает. Проверяю правда на домашнем сервере, рабочего сервера нету сейчас, к сожалению, хотя врятли это на что-то влияет.

**Comment by kilroy98** [comment]
Думаю уже можно закрывать :D
